package com.wygl.sbwygl.bean;


/**
 * Admin generated by MyEclipse Persistence Tools
 */

public class Ba implements java.io.Serializable {

	private Integer id;	
	private String name;
	private String sex;	
	private String persionNo;	
	private String begDate; 	
	private String post;
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getSex() {
		return sex;
	}
	public void setSex(String sex) {
		this.sex = sex;
	}
	public String getPersionNo() {
		return persionNo;
	}
	public void setPersionNo(String persionNo) {
		this.persionNo = persionNo;
	}
	public String getBegDate() {
		return begDate;
	}
	public void setBegDate(String begDate) {
		this.begDate = begDate;
	}
	public String getPost() {
		return post;
	}
	public void setPost(String post) {
		this.post = post;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	
}