package com.wygl.sbwygl.bean;


/**
 * Admin generated by MyEclipse Persistence Tools
 */

public class Pb implements java.io.Serializable {

	private Integer id;
	private String name;	
	private String startTime;	
	private String endTime;
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getStartTime() {
		return startTime;
	}
	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}
	public String getEndTime() {
		return endTime;
	}
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	

	
}