package com.wygl.sbwygl.bean;

/**
 * Admin generated by MyEclipse Persistence Tools
 */

public class Rs implements java.io.Serializable {

	private Integer id;

	private Integer adminType;

	private String adminName;

	private String loginName;

	private String loginPwd;
	
	private String sex;
	
	private String persionNo;
	
	private String begDate; 
	
	private String post;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getAdminType() {
		return adminType;
	}

	public void setAdminType(Integer adminType) {
		this.adminType = adminType;
	}

	public String getAdminName() {
		return adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	public String getLoginName() {
		return loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getLoginPwd() {
		return loginPwd;
	}

	public void setLoginPwd(String loginPwd) {
		this.loginPwd = loginPwd;
	}

	public String getPersionNo() {
		return persionNo;
	}

	public void setPersionNo(String persionNo) {
		this.persionNo = persionNo;
	}

	public String getBegDate() {
		return begDate;
	}

	public void setBegDate(String begDate) {
		this.begDate = begDate;
	}

	public String getPost() {
		return post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	
}